# This is a basic workflow to help you get started with Actions

name: Run ADO to Github Sync with PowerShell

# Controls when the workflow will run
on:
 workflow_dispatch:
 
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - run: |
          ./SyncADOtoGithub.ps1 -GitHubDestinationPAT ${{secrets.GITHUBDESTINATIONPA}} -ADOSourcePAT ${{ secrets.ADOSOURCEPAT}}
          
